# Generated by Django 5.2.17 on 2026-10-04 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "competitions",
            "0002_remove_competition_format_alter_competition_best_of_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Stage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Regular season, Playoffs.",
                        max_length=100,
                        verbose_name="stage name",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            (
                                "round_robin",
                                "Round robin (everyone plays everyone once)",
                            ),
                            (
                                "double_round_robin",
                                "Double round robin (everyone plays everyone twice)",
                            ),
                            ("single_elim", "Single elimination"),
                            ("double_elim", "Double elimination"),
                            ("swiss", "Swiss"),
                            ("custom", "Custom (matches added by hand)"),
                        ],
                        max_length=20,
                        verbose_name="format",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="display order"
                    ),
                ),
                (
                    "best_of",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Leave blank to use the competition's.",
                        null=True,
                        verbose_name="games per match (best of)",
                    ),
                ),
                (
                    "swiss_rounds",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Only for Swiss stages.",
                        null=True,
                        verbose_name="number of Swiss rounds",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Coaches and the public see this stage's matches only once it's published.",
                        verbose_name="published",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="competitions.competition",
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank to include approved teams from every division.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stages",
                        to="competitions.division",
                        verbose_name="division",
                    ),
                ),
            ],
            options={
                "verbose_name": "stage",
                "ordering": ["competition", "order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(
                        help_text="Unique within the stage.",
                        verbose_name="match number",
                    ),
                ),
                (
                    "round_number",
                    models.PositiveSmallIntegerField(default=1, verbose_name="round"),
                ),
                (
                    "round_label",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Week 3, Semifinal.",
                        max_length=60,
                        verbose_name="round name",
                    ),
                ),
                (
                    "bracket",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "—"),
                            ("winners", "Winners bracket"),
                            ("losers", "Losers bracket"),
                            ("final", "Grand final"),
                        ],
                        default="",
                        max_length=10,
                    ),
                ),
                (
                    "home_source_outcome",
                    models.CharField(
                        blank=True,
                        choices=[("winner", "Winner"), ("loser", "Loser")],
                        max_length=10,
                    ),
                ),
                (
                    "away_source_outcome",
                    models.CharField(
                        blank=True,
                        choices=[("winner", "Winner"), ("loser", "Loser")],
                        max_length=10,
                    ),
                ),
                (
                    "play_from",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="play from"
                    ),
                ),
                (
                    "play_by",
                    models.DateTimeField(
                        blank=True,
                        help_text="Deadline for this match.",
                        null=True,
                        verbose_name="play by",
                    ),
                ),
                (
                    "scheduled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="match time"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("bye", "Bye"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                (
                    "cancel_reason",
                    models.CharField(blank=True, max_length=300, verbose_name="reason"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "away",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="competitions.registration",
                        verbose_name="team 2",
                    ),
                ),
                (
                    "away_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="matches.match",
                    ),
                ),
                (
                    "home",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="competitions.registration",
                        verbose_name="team 1",
                    ),
                ),
                (
                    "home_source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="matches.match",
                    ),
                ),
                (
                    "winner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="competitions.registration",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches",
                        to="matches.stage",
                    ),
                ),
            ],
            options={
                "verbose_name": "match",
                "verbose_name_plural": "matches",
                "ordering": ["stage", "round_number", "bracket", "number"],
            },
        ),
        migrations.CreateModel(
            name="StageTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seed", models.PositiveSmallIntegerField()),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stage_entries",
                        to="competitions.registration",
                    ),
                ),
                (
                    "stage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="matches.stage",
                    ),
                ),
            ],
            options={
                "ordering": ["stage", "seed"],
            },
        ),
        migrations.CreateModel(
            name="TimeProposal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proposed_time", models.DateTimeField(verbose_name="proposed time")),
                (
                    "note",
                    models.CharField(blank=True, max_length=300, verbose_name="note"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting for the other team"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("withdrawn", "Withdrawn"),
                            ("replaced", "Replaced by a newer proposal"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("response_note", models.CharField(blank=True, max_length=300)),
                (
                    "match",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="matches.match",
                    ),
                ),
                (
                    "proposed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proposing_team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="competitions.registration",
                    ),
                ),
                (
                    "responded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="match",
            constraint=models.UniqueConstraint(
                fields=("stage", "number"), name="unique_match_number_per_stage"
            ),
        ),
        migrations.AddConstraint(
            model_name="stageteam",
            constraint=models.UniqueConstraint(
                fields=("stage", "registration"), name="team_once_per_stage"
            ),
        ),
        migrations.AddConstraint(
            model_name="stageteam",
            constraint=models.UniqueConstraint(
                fields=("stage", "seed"), name="unique_seed_per_stage"
            ),
        ),
    ]
