# Generated by Django 5.2.17 on 2026-10-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this person proved they can receive email at this address.",
                null=True,
            ),
        ),
    ]
