# Generated by Django 5.2.17 on 2026-10-04 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="when"
                    ),
                ),
                ("actor_label", models.CharField(blank=True, max_length=255)),
                (
                    "action",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="action"
                    ),
                ),
                ("summary", models.CharField(max_length=500, verbose_name="summary")),
                ("target_type", models.CharField(blank=True, max_length=50)),
                ("target_id", models.CharField(blank=True, max_length=50)),
                ("target_label", models.CharField(blank=True, max_length=255)),
                ("changes", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="who",
                    ),
                ),
            ],
            options={
                "verbose_name": "activity log entry",
                "verbose_name_plural": "activity log",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="audit_audit_target__59bbff_idx",
                    )
                ],
            },
        ),
    ]
