# Generated by Django 5.2.17 on 2026-10-04 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolBoard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, unique=True, verbose_name="name"),
                ),
                (
                    "email_domains",
                    models.TextField(
                        blank=True,
                        help_text="One per line, e.g. exampleboard.on.ca. Used only to flag coach requests from other addresses for a closer look; it never approves anyone automatically.",
                        verbose_name="staff email domains",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "school board",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="school name")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("elementary", "Elementary"),
                            ("secondary", "Secondary"),
                            ("combined", "Combined (elementary and secondary)"),
                        ],
                        max_length=20,
                        verbose_name="level",
                    ),
                ),
                ("city", models.CharField(max_length=100, verbose_name="city or town")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Turn off instead of deleting, so the school's history is kept.",
                        verbose_name="active",
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Only OSEA administrators see this.",
                        verbose_name="OSEA notes",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "board",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank for independent schools.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schools",
                        to="schools.schoolboard",
                        verbose_name="school board",
                    ),
                ),
            ],
            options={
                "verbose_name": "school",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SchoolYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="For example 2026–27.",
                        max_length=20,
                        unique=True,
                        verbose_name="name",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="start date")),
                ("end_date", models.DateField(verbose_name="end date")),
                (
                    "is_current",
                    models.BooleanField(
                        default=False,
                        help_text="Dashboards and membership checks use the current school year.",
                        verbose_name="current school year",
                    ),
                ),
            ],
            options={
                "verbose_name": "school year",
                "ordering": ["-start_date"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_current", True)),
                        fields=("is_current",),
                        name="one_current_school_year",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("end_date__gt", models.F("start_date"))),
                        name="school_year_ends_after_start",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("exempt", "Exception granted"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="amount paid ($)",
                    ),
                ),
                (
                    "paid_on",
                    models.DateField(blank=True, null=True, verbose_name="date paid"),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True,
                        help_text="Cheque number, e-transfer reference or invoice number.",
                        max_length=100,
                        verbose_name="payment reference",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Required when granting an exception.",
                        verbose_name="notes",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="schools.school",
                    ),
                ),
                (
                    "school_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="memberships",
                        to="schools.schoolyear",
                        verbose_name="school year",
                    ),
                ),
            ],
            options={
                "verbose_name": "membership",
                "ordering": ["-school_year__start_date", "school__name"],
            },
        ),
        migrations.CreateModel(
            name="CoachAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "requested_school_name",
                    models.CharField(
                        blank=True,
                        help_text="School name, city and school board, if your school isn't in the list.",
                        max_length=300,
                        verbose_name="school not in the list",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        help_text="For example: Grade 10 Computer Studies teacher.",
                        max_length=200,
                        verbose_name="your role at the school",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting for approval"),
                            ("approved", "Approved"),
                            ("declined", "Declined"),
                            ("revoked", "Access removed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decision_note",
                    models.TextField(
                        blank=True,
                        help_text="Shown to the coach. Required when declining or removing access.",
                        verbose_name="message to the coach",
                    ),
                ),
                (
                    "coach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="school_access",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coach_access",
                        to="schools.school",
                        verbose_name="school",
                    ),
                ),
            ],
            options={
                "verbose_name": "coach access",
                "verbose_name_plural": "coach access",
                "ordering": ["-requested_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("school__isnull", False)),
                        fields=("coach", "school"),
                        name="one_access_per_coach_school",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("school__isnull", False),
                            models.Q(("requested_school_name", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="access_names_a_school",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="school",
            constraint=models.UniqueConstraint(
                fields=("name", "city"), name="unique_school_name_city"
            ),
        ),
        migrations.AddConstraint(
            model_name="membership",
            constraint=models.UniqueConstraint(
                fields=("school", "school_year"), name="one_membership_per_school_year"
            ),
        ),
    ]
