# Generated by Django 5.2.17 on 2026-10-04 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="first name"),
                ),
                (
                    "last_initial",
                    models.CharField(max_length=2, verbose_name="last initial"),
                ),
                (
                    "grade",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Grade 1"),
                            (2, "Grade 2"),
                            (3, "Grade 3"),
                            (4, "Grade 4"),
                            (5, "Grade 5"),
                            (6, "Grade 6"),
                            (7, "Grade 7"),
                            (8, "Grade 8"),
                            (9, "Grade 9"),
                            (10, "Grade 10"),
                            (11, "Grade 11"),
                            (12, "Grade 12"),
                        ],
                        verbose_name="grade",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Turn off when the student leaves. Their past rosters are kept.",
                        verbose_name="still at this school",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "verbose_name": "student",
                "ordering": ["first_name", "last_initial"],
            },
        ),
    ]
