# Generated by Django 5.2.17 on 2026-10-04 13:15

import django.contrib.postgres.fields
import django.db.models.deletion
import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0002_student"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="name"),
                ),
                (
                    "gamer_tag_label",
                    models.CharField(
                        default="Gamer tag",
                        help_text="Shown on roster forms, e.g. Riot ID, Epic username, Nintendo Switch name.",
                        max_length=50,
                        verbose_name="what the game calls a player name",
                    ),
                ),
                (
                    "rank_label",
                    models.CharField(
                        default="Rank",
                        help_text="e.g. Rank, Competitive rank.",
                        max_length=50,
                        verbose_name="what the game calls a rank",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="active")),
            ],
            options={
                "verbose_name": "game",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Competition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Valorant Winter League 2027.",
                        max_length=150,
                        verbose_name="competition name",
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Winter 2027.",
                        max_length=50,
                        verbose_name="season",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="public description"),
                ),
                (
                    "rules_url",
                    models.URLField(
                        blank=True,
                        help_text="Link to the rulebook for coaches.",
                        verbose_name="rules link",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[
                            ("league", "League (round robin)"),
                            ("bracket", "Bracket / playoffs"),
                            ("judged", "Judged challenge"),
                            ("other", "Other"),
                        ],
                        default="league",
                        max_length=20,
                        verbose_name="format",
                    ),
                ),
                (
                    "best_of",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Leave blank if it doesn't apply.",
                        null=True,
                        verbose_name="games per match (best of)",
                    ),
                ),
                (
                    "registration_opens_at",
                    models.DateTimeField(verbose_name="registration opens"),
                ),
                (
                    "registration_closes_at",
                    models.DateTimeField(verbose_name="registration closes"),
                ),
                (
                    "roster_deadline",
                    models.DateTimeField(
                        help_text="Last moment coaches can request roster changes. Must be on or after registration closes.",
                        verbose_name="roster deadline",
                    ),
                ),
                (
                    "allowed_levels",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("elementary", "Elementary"),
                                ("secondary", "Secondary"),
                                ("combined", "Combined (elementary and secondary)"),
                            ],
                            max_length=20,
                        ),
                        default=list,
                        size=None,
                        verbose_name="school levels that can enter",
                    ),
                ),
                (
                    "min_grade",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Grade 1"),
                            (2, "Grade 2"),
                            (3, "Grade 3"),
                            (4, "Grade 4"),
                            (5, "Grade 5"),
                            (6, "Grade 6"),
                            (7, "Grade 7"),
                            (8, "Grade 8"),
                            (9, "Grade 9"),
                            (10, "Grade 10"),
                            (11, "Grade 11"),
                            (12, "Grade 12"),
                        ],
                        verbose_name="lowest grade",
                    ),
                ),
                (
                    "max_grade",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Grade 1"),
                            (2, "Grade 2"),
                            (3, "Grade 3"),
                            (4, "Grade 4"),
                            (5, "Grade 5"),
                            (6, "Grade 6"),
                            (7, "Grade 7"),
                            (8, "Grade 8"),
                            (9, "Grade 9"),
                            (10, "Grade 10"),
                            (11, "Grade 11"),
                            (12, "Grade 12"),
                        ],
                        verbose_name="highest grade",
                    ),
                ),
                (
                    "players_per_team",
                    models.PositiveSmallIntegerField(
                        help_text="How many play at once, e.g. 5 for Valorant, 1 for singles.",
                        verbose_name="players in a match",
                    ),
                ),
                (
                    "roster_min",
                    models.PositiveSmallIntegerField(
                        verbose_name="minimum roster size"
                    ),
                ),
                (
                    "roster_max",
                    models.PositiveSmallIntegerField(
                        help_text="Including substitutes.",
                        verbose_name="maximum roster size",
                    ),
                ),
                (
                    "max_teams",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Leave blank for no limit.",
                        null=True,
                        verbose_name="maximum teams in the competition",
                    ),
                ),
                (
                    "max_teams_per_school",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Leave blank for no limit.",
                        null=True,
                        verbose_name="maximum teams per school",
                    ),
                ),
                (
                    "require_gamer_tag",
                    models.BooleanField(
                        default=True, verbose_name="require each player's in-game name"
                    ),
                ),
                (
                    "rank_requirement",
                    models.CharField(
                        choices=[
                            ("off", "Don't ask"),
                            ("optional", "Ask, but optional"),
                            ("required", "Required"),
                        ],
                        default="off",
                        max_length=10,
                        verbose_name="ask for each player's rank",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Coaches and the public can only see published competitions.",
                        verbose_name="published",
                    ),
                ),
                (
                    "show_teams_publicly",
                    models.BooleanField(
                        default=False,
                        verbose_name="show approved team and school names publicly",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="schools.schoolyear",
                        verbose_name="school year",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="competitions",
                        to="competitions.game",
                        verbose_name="game",
                    ),
                ),
            ],
            options={
                "verbose_name": "competition",
                "ordering": ["-registration_opens_at", "name"],
            },
        ),
        migrations.CreateModel(
            name="Division",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Bronze–Gold, Middle School.",
                        max_length=100,
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="description"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="display order"
                    ),
                ),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="divisions",
                        to="competitions.competition",
                    ),
                ),
            ],
            options={
                "verbose_name": "division",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "team_name",
                    models.CharField(
                        help_text="Shown publicly once approved.",
                        max_length=60,
                        verbose_name="team name",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("changes_requested", "Changes requested"),
                            ("approved", "Approved"),
                            ("waitlisted", "Waitlisted"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "admin_message",
                    models.TextField(blank=True, verbose_name="message from OSEA"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("consent_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registrations",
                        to="competitions.competition",
                    ),
                ),
                (
                    "consent_confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registrations",
                        to="competitions.division",
                        verbose_name="division",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registrations",
                        to="schools.school",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "registration",
                "ordering": ["competition", "team_name"],
            },
        ),
        migrations.CreateModel(
            name="RosterChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gamer_tag",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        verbose_name="in-game name of the player being added",
                    ),
                ),
                (
                    "rank",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        verbose_name="rank of the player being added",
                    ),
                ),
                ("reason", models.CharField(max_length=300, verbose_name="reason")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting for approval"),
                            ("approved", "Approved"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decision_note",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="message to the coach"
                    ),
                ),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "player_in",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="schools.student",
                        verbose_name="player to add",
                    ),
                ),
                (
                    "player_out",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="schools.student",
                        verbose_name="player to remove",
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster_changes",
                        to="competitions.registration",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
        migrations.CreateModel(
            name="RosterEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gamer_tag",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="in-game name"
                    ),
                ),
                (
                    "rank",
                    models.CharField(blank=True, max_length=40, verbose_name="rank"),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster",
                        to="competitions.registration",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roster_entries",
                        to="schools.student",
                    ),
                ),
            ],
            options={
                "verbose_name": "roster entry",
                "verbose_name_plural": "roster entries",
                "ordering": ["student__first_name", "student__last_initial"],
            },
        ),
        migrations.AddConstraint(
            model_name="division",
            constraint=models.UniqueConstraint(
                fields=("competition", "name"), name="unique_division_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="registration",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("team_name"),
                models.F("competition"),
                name="unique_team_name_per_competition",
            ),
        ),
        migrations.AddConstraint(
            model_name="rosterchange",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("player_in__isnull", False),
                    ("player_out__isnull", False),
                    _connector="OR",
                ),
                name="change_names_a_player",
            ),
        ),
        migrations.AddConstraint(
            model_name="rosterentry",
            constraint=models.UniqueConstraint(
                fields=("registration", "student"), name="student_once_per_roster"
            ),
        ),
    ]
