# Generated by Django 5.2.17 on 2026-10-04 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("competitions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="competition",
            name="format",
        ),
        migrations.AlterField(
            model_name="competition",
            name="best_of",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Default for every stage; a stage can override it. Leave blank if it doesn't apply.",
                null=True,
                verbose_name="games per match (best of)",
            ),
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="title")),
                (
                    "body",
                    models.TextField(
                        help_text="Links are clickable.", verbose_name="message"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Leave off for coach-only messages.",
                        verbose_name="also show on the public competition page",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "competition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="competitions.competition",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "division",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank to send to the whole competition.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="announcements",
                        to="competitions.division",
                        verbose_name="division",
                    ),
                ),
            ],
            options={
                "verbose_name": "announcement",
                "ordering": ["-created_at"],
            },
        ),
    ]
